import { Team, LeagueId } from './types';

export const TEAMS: Team[] = [
  // --- PREMIER LEAGUE ---
  {
    id: 'arsenal',
    name: 'Arsenal',
    shortName: 'Arsenal',
    code: 'ARS',
    leagueId: 'premier-league',
    leagueName: 'Premier League',
    stadium: 'Emirates Stadium',
    city: 'London',
    country: 'England',
    monogram: 'AFC',
  },
  {
    id: 'man-city',
    name: 'Manchester City',
    shortName: 'Man City',
    code: 'MCI',
    leagueId: 'premier-league',
    leagueName: 'Premier League',
    stadium: 'Etihad Stadium',
    city: 'Manchester',
    country: 'England',
    monogram: 'MCFC',
  },
  {
    id: 'liverpool',
    name: 'Liverpool',
    shortName: 'Liverpool',
    code: 'LIV',
    leagueId: 'premier-league',
    leagueName: 'Premier League',
    stadium: 'Anfield',
    city: 'Liverpool',
    country: 'England',
    monogram: 'LFC',
  },
  {
    id: 'chelsea',
    name: 'Chelsea',
    shortName: 'Chelsea',
    code: 'CHE',
    leagueId: 'premier-league',
    leagueName: 'Premier League',
    stadium: 'Stamford Bridge',
    city: 'London',
    country: 'England',
    monogram: 'CFC',
  },
  {
    id: 'tottenham',
    name: 'Tottenham Hotspur',
    shortName: 'Tottenham',
    code: 'TOT',
    leagueId: 'premier-league',
    leagueName: 'Premier League',
    stadium: 'Tottenham Hotspur Stadium',
    city: 'London',
    country: 'England',
    monogram: 'THFC',
  },
  {
    id: 'man-united',
    name: 'Manchester United',
    shortName: 'Man United',
    code: 'MUN',
    leagueId: 'premier-league',
    leagueName: 'Premier League',
    stadium: 'Old Trafford',
    city: 'Manchester',
    country: 'England',
    monogram: 'MUFC',
  },
  {
    id: 'aston-villa',
    name: 'Aston Villa',
    shortName: 'Aston Villa',
    code: 'AVL',
    leagueId: 'premier-league',
    leagueName: 'Premier League',
    stadium: 'Villa Park',
    city: 'Birmingham',
    country: 'England',
    monogram: 'AVFC',
  },
  {
    id: 'newcastle',
    name: 'Newcastle United',
    shortName: 'Newcastle',
    code: 'NEW',
    leagueId: 'premier-league',
    leagueName: 'Premier League',
    stadium: 'St. James Park',
    city: 'Newcastle',
    country: 'England',
    monogram: 'NUFC',
  },
  {
    id: 'brighton',
    name: 'Brighton & Hove Albion',
    shortName: 'Brighton',
    code: 'BHA',
    leagueId: 'premier-league',
    leagueName: 'Premier League',
    stadium: 'Amex Stadium',
    city: 'Brighton',
    country: 'England',
    monogram: 'BHAFC',
  },
  {
    id: 'west-ham',
    name: 'West Ham United',
    shortName: 'West Ham',
    code: 'WHU',
    leagueId: 'premier-league',
    leagueName: 'Premier League',
    stadium: 'London Stadium',
    city: 'London',
    country: 'England',
    monogram: 'WHUFC',
  },

  // --- LA LIGA ---
  {
    id: 'real-madrid',
    name: 'Real Madrid',
    shortName: 'Real Madrid',
    code: 'RMA',
    leagueId: 'la-liga',
    leagueName: 'La Liga',
    stadium: 'Santiago Bernabéu',
    city: 'Madrid',
    country: 'Spain',
    monogram: 'RM',
  },
  {
    id: 'barcelona',
    name: 'FC Barcelona',
    shortName: 'Barcelona',
    code: 'FCB',
    leagueId: 'la-liga',
    leagueName: 'La Liga',
    stadium: 'Spotify Camp Nou',
    city: 'Barcelona',
    country: 'Spain',
    monogram: 'FCB',
  },
  {
    id: 'atletico-madrid',
    name: 'Atlético Madrid',
    shortName: 'Atlético',
    code: 'ATM',
    leagueId: 'la-liga',
    leagueName: 'La Liga',
    stadium: 'Cívitas Metropolitano',
    city: 'Madrid',
    country: 'Spain',
    monogram: 'ATM',
  },
  {
    id: 'athletic-club',
    name: 'Athletic Club',
    shortName: 'Athletic Club',
    code: 'ATH',
    leagueId: 'la-liga',
    leagueName: 'La Liga',
    stadium: 'San Mamés',
    city: 'Bilbao',
    country: 'Spain',
    monogram: 'ATH',
  },
  {
    id: 'real-sociedad',
    name: 'Real Sociedad',
    shortName: 'Real Sociedad',
    code: 'RSO',
    leagueId: 'la-liga',
    leagueName: 'La Liga',
    stadium: 'Reale Arena',
    city: 'San Sebastián',
    country: 'Spain',
    monogram: 'RSO',
  },
  {
    id: 'girona',
    name: 'Girona FC',
    shortName: 'Girona',
    code: 'GIR',
    leagueId: 'la-liga',
    leagueName: 'La Liga',
    stadium: 'Estadi Montilivi',
    city: 'Girona',
    country: 'Spain',
    monogram: 'GIR',
  },
  {
    id: 'villarreal',
    name: 'Villarreal CF',
    shortName: 'Villarreal',
    code: 'VIL',
    leagueId: 'la-liga',
    leagueName: 'La Liga',
    stadium: 'Estadio de la Cerámica',
    city: 'Villarreal',
    country: 'Spain',
    monogram: 'VCF',
  },
  {
    id: 'real-betis',
    name: 'Real Betis',
    shortName: 'Betis',
    code: 'BET',
    leagueId: 'la-liga',
    leagueName: 'La Liga',
    stadium: 'Benito Villamarín',
    city: 'Seville',
    country: 'Spain',
    monogram: 'RBB',
  },

  // --- UEFA CHAMPIONS LEAGUE GIANTS ---
  {
    id: 'bayern-munich',
    name: 'Bayern München',
    shortName: 'Bayern',
    code: 'BAY',
    leagueId: 'champions-league',
    leagueName: 'Champions League',
    stadium: 'Allianz Arena',
    city: 'Munich',
    country: 'Germany',
    monogram: 'FCB',
  },
  {
    id: 'psg',
    name: 'Paris Saint-Germain',
    shortName: 'PSG',
    code: 'PSG',
    leagueId: 'champions-league',
    leagueName: 'Champions League',
    stadium: 'Parc des Princes',
    city: 'Paris',
    country: 'France',
    monogram: 'PSG',
  },
  {
    id: 'inter-milan',
    name: 'Inter Milan',
    shortName: 'Inter',
    code: 'INT',
    leagueId: 'champions-league',
    leagueName: 'Champions League',
    stadium: 'San Siro',
    city: 'Milan',
    country: 'Italy',
    monogram: 'INT',
  },
  {
    id: 'leverkusen',
    name: 'Bayer 04 Leverkusen',
    shortName: 'Leverkusen',
    code: 'B04',
    leagueId: 'champions-league',
    leagueName: 'Champions League',
    stadium: 'BayArena',
    city: 'Leverkusen',
    country: 'Germany',
    monogram: 'B04',
  },
  {
    id: 'dortmund',
    name: 'Borussia Dortmund',
    shortName: 'Dortmund',
    code: 'BVB',
    leagueId: 'champions-league',
    leagueName: 'Champions League',
    stadium: 'Signal Iduna Park',
    city: 'Dortmund',
    country: 'Germany',
    monogram: 'BVB',
  },
  {
    id: 'juventus',
    name: 'Juventus',
    shortName: 'Juventus',
    code: 'JUV',
    leagueId: 'champions-league',
    leagueName: 'Champions League',
    stadium: 'Allianz Stadium',
    city: 'Turin',
    country: 'Italy',
    monogram: 'JUVE',
  },
];

export const getTeamById = (id: string): Team | undefined => {
  return TEAMS.find((t) => t.id === id);
};

export const getTeamsByLeague = (leagueId: LeagueId | 'all'): Team[] => {
  if (leagueId === 'all') return TEAMS;
  return TEAMS.filter((t) => t.leagueId === leagueId);
};
