import { Team, LeagueId } from './types';

export const TEAMS: Team[] = [
  // --- PREMIER LEAGUE ---
  {
    id: 'arsenal',
    name: 'Arsenal',
    shortName: 'Arsenal',
    code: 'ARS',
    leagueId: 'premier-league',
    leagueName: 'Premier League',
    stadium: 'Emirates Stadium',
    city: 'London',
    country: 'England',
    monogram: 'AFC',
    primaryColor: '#EF0107',
    secondaryColor: '#FFFFFF',
    crest: 'https://media.api-sports.io/football/teams/42.png',
  },
  {
    id: 'man-city',
    name: 'Manchester City',
    shortName: 'Man City',
    code: 'MCI',
    leagueId: 'premier-league',
    leagueName: 'Premier League',
    stadium: 'Etihad Stadium',
    city: 'Manchester',
    country: 'England',
    monogram: 'MCFC',
    primaryColor: '#6CABDD',
    secondaryColor: '#1C2C5B',
    crest: 'https://media.api-sports.io/football/teams/50.png',
  },
  {
    id: 'liverpool',
    name: 'Liverpool',
    shortName: 'Liverpool',
    code: 'LIV',
    leagueId: 'premier-league',
    leagueName: 'Premier League',
    stadium: 'Anfield',
    city: 'Liverpool',
    country: 'England',
    monogram: 'LFC',
    primaryColor: '#C8102E',
    secondaryColor: '#00B2A9',
    crest: 'https://media.api-sports.io/football/teams/40.png',
  },
  {
    id: 'chelsea',
    name: 'Chelsea',
    shortName: 'Chelsea',
    code: 'CHE',
    leagueId: 'premier-league',
    leagueName: 'Premier League',
    stadium: 'Stamford Bridge',
    city: 'London',
    country: 'England',
    monogram: 'CFC',
    primaryColor: '#034694',
    secondaryColor: '#EE242C',
    crest: 'https://media.api-sports.io/football/teams/49.png',
  },
  {
    id: 'tottenham',
    name: 'Tottenham Hotspur',
    shortName: 'Tottenham',
    code: 'TOT',
    leagueId: 'premier-league',
    leagueName: 'Premier League',
    stadium: 'Tottenham Hotspur Stadium',
    city: 'London',
    country: 'England',
    monogram: 'THFC',
    primaryColor: '#132257',
    secondaryColor: '#FFFFFF',
    crest: 'https://media.api-sports.io/football/teams/47.png',
  },
  {
    id: 'man-united',
    name: 'Manchester United',
    shortName: 'Man United',
    code: 'MUN',
    leagueId: 'premier-league',
    leagueName: 'Premier League',
    stadium: 'Old Trafford',
    city: 'Manchester',
    country: 'England',
    monogram: 'MUFC',
    primaryColor: '#DA291C',
    secondaryColor: '#FBE122',
    crest: 'https://media.api-sports.io/football/teams/33.png',
  },
  {
    id: 'aston-villa',
    name: 'Aston Villa',
    shortName: 'Aston Villa',
    code: 'AVL',
    leagueId: 'premier-league',
    leagueName: 'Premier League',
    stadium: 'Villa Park',
    city: 'Birmingham',
    country: 'England',
    monogram: 'AVFC',
    primaryColor: '#670E36',
    secondaryColor: '#95BFE5',
    crest: 'https://media.api-sports.io/football/teams/66.png',
  },
  {
    id: 'newcastle',
    name: 'Newcastle United',
    shortName: 'Newcastle',
    code: 'NEW',
    leagueId: 'premier-league',
    leagueName: 'Premier League',
    stadium: 'St. James Park',
    city: 'Newcastle',
    country: 'England',
    monogram: 'NUFC',
    primaryColor: '#241F20',
    secondaryColor: '#FFFFFF',
    crest: 'https://media.api-sports.io/football/teams/34.png',
  },

  // --- LA LIGA ---
  {
    id: 'real-madrid',
    name: 'Real Madrid',
    shortName: 'Real Madrid',
    code: 'RMA',
    leagueId: 'la-liga',
    leagueName: 'La Liga',
    stadium: 'Santiago Bernabéu',
    city: 'Madrid',
    country: 'Spain',
    monogram: 'RM',
    primaryColor: '#FFFFFF',
    secondaryColor: '#FEBE10',
    crest: 'https://media.api-sports.io/football/teams/541.png',
  },
  {
    id: 'barcelona',
    name: 'FC Barcelona',
    shortName: 'Barcelona',
    code: 'FCB',
    leagueId: 'la-liga',
    leagueName: 'La Liga',
    stadium: 'Spotify Camp Nou',
    city: 'Barcelona',
    country: 'Spain',
    monogram: 'FCB',
    primaryColor: '#004D98',
    secondaryColor: '#A50044',
    crest: 'https://media.api-sports.io/football/teams/529.png',
  },
  {
    id: 'atletico-madrid',
    name: 'Atlético Madrid',
    shortName: 'Atlético',
    code: 'ATM',
    leagueId: 'la-liga',
    leagueName: 'La Liga',
    stadium: 'Cívitas Metropolitano',
    city: 'Madrid',
    country: 'Spain',
    monogram: 'ATM',
    primaryColor: '#CB3524',
    secondaryColor: '#272E61',
    crest: 'https://media.api-sports.io/football/teams/530.png',
  },
  {
    id: 'athletic-club',
    name: 'Athletic Club',
    shortName: 'Athletic Club',
    code: 'ATH',
    leagueId: 'la-liga',
    leagueName: 'La Liga',
    stadium: 'San Mamés',
    city: 'Bilbao',
    country: 'Spain',
    monogram: 'ATH',
    primaryColor: '#EE2524',
    secondaryColor: '#FFFFFF',
    crest: 'https://media.api-sports.io/football/teams/531.png',
  },
  {
    id: 'real-sociedad',
    name: 'Real Sociedad',
    shortName: 'Real Sociedad',
    code: 'RSO',
    leagueId: 'la-liga',
    leagueName: 'La Liga',
    stadium: 'Reale Arena',
    city: 'San Sebastián',
    country: 'Spain',
    monogram: 'RSO',
    primaryColor: '#0067B1',
    secondaryColor: '#FFFFFF',
    crest: 'https://media.api-sports.io/football/teams/548.png',
  },
  {
    id: 'girona',
    name: 'Girona FC',
    shortName: 'Girona',
    code: 'GIR',
    leagueId: 'la-liga',
    leagueName: 'La Liga',
    stadium: 'Estadi Montilivi',
    city: 'Girona',
    country: 'Spain',
    monogram: 'GIR',
    primaryColor: '#CC0000',
    secondaryColor: '#FFFFFF',
    crest: 'https://media.api-sports.io/football/teams/547.png',
  },
  {
    id: 'villarreal',
    name: 'Villarreal CF',
    shortName: 'Villarreal',
    code: 'VIL',
    leagueId: 'la-liga',
    leagueName: 'La Liga',
    stadium: 'Estadio de la Cerámica',
    city: 'Villarreal',
    country: 'Spain',
    monogram: 'VCF',
    primaryColor: '#FDE100',
    secondaryColor: '#005CA9',
    crest: 'https://media.api-sports.io/football/teams/533.png',
  },

  // --- CHAMPIONS LEAGUE (Europe Continent Giants) ---
  {
    id: 'bayern-munich',
    name: 'Bayern München',
    shortName: 'Bayern',
    code: 'BAY',
    leagueId: 'champions-league',
    leagueName: 'Champions League',
    stadium: 'Allianz Arena',
    city: 'Munich',
    country: 'Germany',
    monogram: 'FCB',
    primaryColor: '#DC052D',
    secondaryColor: '#0066B2',
    crest: 'https://media.api-sports.io/football/teams/157.png',
  },
  {
    id: 'psg',
    name: 'Paris Saint-Germain',
    shortName: 'PSG',
    code: 'PSG',
    leagueId: 'champions-league',
    leagueName: 'Champions League',
    stadium: 'Parc des Princes',
    city: 'Paris',
    country: 'France',
    monogram: 'PSG',
    primaryColor: '#004170',
    secondaryColor: '#DA291C',
    crest: 'https://media.api-sports.io/football/teams/85.png',
  },
  {
    id: 'inter-milan',
    name: 'Inter Milan',
    shortName: 'Inter',
    code: 'INT',
    leagueId: 'champions-league',
    leagueName: 'Champions League',
    stadium: 'San Siro',
    city: 'Milan',
    country: 'Italy',
    monogram: 'INT',
    primaryColor: '#0066B2',
    secondaryColor: '#000000',
    crest: 'https://media.api-sports.io/football/teams/505.png',
  },
  {
    id: 'leverkusen',
    name: 'Bayer 04 Leverkusen',
    shortName: 'Leverkusen',
    code: 'B04',
    leagueId: 'champions-league',
    leagueName: 'Champions League',
    stadium: 'BayArena',
    city: 'Leverkusen',
    country: 'Germany',
    monogram: 'B04',
    primaryColor: '#E32221',
    secondaryColor: '#000000',
    crest: 'https://media.api-sports.io/football/teams/168.png',
  },
  {
    id: 'dortmund',
    name: 'Borussia Dortmund',
    shortName: 'Dortmund',
    code: 'BVB',
    leagueId: 'champions-league',
    leagueName: 'Champions League',
    stadium: 'Signal Iduna Park',
    city: 'Dortmund',
    country: 'Germany',
    monogram: 'BVB',
    primaryColor: '#FDE100',
    secondaryColor: '#000000',
    crest: 'https://media.api-sports.io/football/teams/165.png',
  },
  {
    id: 'juventus',
    name: 'Juventus',
    shortName: 'Juventus',
    code: 'JUV',
    leagueId: 'champions-league',
    leagueName: 'Champions League',
    stadium: 'Allianz Stadium',
    city: 'Turin',
    country: 'Italy',
    monogram: 'JUVE',
    primaryColor: '#000000',
    secondaryColor: '#FFFFFF',
    crest: 'https://media.api-sports.io/football/teams/496.png',
  },
];

export const getTeamById = (id: string): Team | undefined => {
  return TEAMS.find((t) => t.id === id);
};

export const getTeamsByLeague = (leagueId: LeagueId | 'all'): Team[] => {
  if (leagueId === 'all') return TEAMS;
  return TEAMS.filter((t) => t.leagueId === leagueId);
};
